language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx

cache:
 - ccache
 - apt
 - bundler

before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - iflin sudo apt-get install libicu-dev libfftw3-dev libxt-dev pkg-config libstdc++5
 - git clone --depth 1 https://github.com/supercollider/supercollider.git
 - cd supercollider
 - git submodule update --init --depth 1 external_libraries/nova-tt external_libraries/nova-simd
 - cd ..

before_script:
 - mkdir BUILD && cd BUILD
 - cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/mkplugins -DCMAKE_BUILD_TYPE="Release" -DSC_PATH=../supercollider -DSUPERNOVA=ON ..

script:
 - iflin make -j2
 - ifmac make install
 - ifmac mkdir -p $HOME/artifacts
 - ifmac zip -q -r $HOME/artifacts/mkplugins-$TRAVIS_COMMIT.zip mkplugins

before_deploy:
 # required for github releases
 - git fetch --tags
 - export BUILD_PREFIX=$TRAVIS_REPO_SLUG/$TRAVIS_OS_NAME
 - export FWD_HTML='<html><head><meta http-equiv="refresh" content="0; url='$S3_URL'" /></head></html>'
 # put everything to be archived in artifacts/
 - mkdir -p "$HOME/artifacts/${TRAVIS_BRANCH%/*}"
 - mkdir -p "$HOME/artifacts/${TRAVIS_TAG%/*}"
 - echo $FWD_HTML > $HOME/artifacts/$TRAVIS_BRANCH-latest.html
 - 'if [[ $TRAVIS_TAG != "head" ]]; then echo $FWD_HTML > $HOME/artifacts/$TRAVIS_TAG.html; fi;'

deploy:
# github releases - only tags
 - provider: releases
   api_key: $GITHUB_KEY
   file: $HOME/artifacts/Plugins-$TRAVIS_COMMIT.zip
   prerelease: true
   skip_cleanup: true
   on:
     condition: $TRAVIS_OS_NAME = osx && ! -z $GITHUB_KEY
     tags: true
     all_branches: true
after_deploy:
notifications:
  on_success: change
  on_failure: change
  webhooks:
    urls:
    on_success: change
    on_failure: always
